import {PGlite} from '@electric-sql/pglite';
import {vector} from '@electric-sql/pglite-pgvector';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const pg=new PGlite({extensions:{vector}});
await pg.exec(`create schema extensions; create schema auth; create schema storage;
create role anon; create role authenticated;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema public,auth,extensions,storage to authenticated,anon;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
alter table storage.objects enable row level security;
create function storage.foldername(name text) returns text[] language sql as $$select string_to_array(name,'/')$$;
grant select,insert,update,delete on storage.objects to authenticated;
insert into auth.users values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');`);
await pg.exec(fs.readFileSync(new URL('../supabase/schema.sql',import.meta.url),'utf8'));
await pg.exec(`set role authenticated;set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';`);
let saved=await pg.query(`select public.mentora_save_workspace($1::jsonb,0) as result`,[JSON.stringify({subjects:[{name:'Private subject'}],assignments:[{id:'a',title:'Tomorrow',due:new Date(Date.now()+3600000).toISOString(),done:false}]})]);
assert.equal(saved.rows[0].result.version,1);
await assert.rejects(()=>pg.query(`select public.mentora_save_workspace('{}'::jsonb,0)`),/Workspace changed/);
for(let i=0;i<20;i++)assert.equal((await pg.query(`select public.mentora_reserve_ai() as ok`)).rows[0].ok,true);
assert.equal((await pg.query(`select public.mentora_reserve_ai() as ok`)).rows[0].ok,false);
await pg.exec(`insert into public.mentora_notes(id,name,path,pages,embedding_model) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Private.pdf','11111111-1111-4111-8111-111111111111/a.pdf',1,'test');`);
await pg.exec(`insert into storage.objects(bucket_id,name) values('mentora-pdfs','11111111-1111-4111-8111-111111111111/a.pdf');`);
await pg.exec(`set request.jwt.claim.sub='22222222-2222-4222-8222-222222222222';`);
assert.equal((await pg.query('select * from public.mentora_workspaces')).rows.length,0);
assert.equal((await pg.query('select * from public.mentora_notes')).rows.length,0);
assert.equal((await pg.query('select * from storage.objects')).rows.length,0);
await assert.rejects(()=>pg.exec(`insert into public.mentora_workspaces(user_id,data) values('11111111-1111-4111-8111-111111111111','{}')`),/row-level security/);
await assert.rejects(()=>pg.exec(`insert into storage.objects(bucket_id,name) values('mentora-pdfs','11111111-1111-4111-8111-111111111111/evil.pdf')`),/row-level security/);
await assert.rejects(()=>pg.exec(`select public.mentora_create_reminders()`),/permission denied/);
// Malformed direct client data cannot block the reminder job.
await pg.query(`select public.mentora_save_workspace($1::jsonb,0)`,[JSON.stringify({assignments:[{id:'bad',title:'bad',due:'not a date',done:false}]})]);
await pg.exec('reset role;select public.mentora_create_reminders();select public.mentora_create_reminders();');
assert.equal((await pg.query('select * from public.mentora_notifications')).rows.length,1);
await pg.exec(`set role authenticated;set request.jwt.claim.sub='22222222-2222-4222-8222-222222222222';`);
assert.equal((await pg.query('select * from public.mentora_notifications')).rows.length,0);
console.log('PASS: full schema, private workspace/notes/storage, blocked cross-user writes, optimistic versions, daily quota, reminder permissions and deduplication, malformed-record isolation.');
await pg.close();
